steps:
  # 1. 构建 Docker 镜像
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/linear-algebra-mastery:$COMMIT_SHA', '.']

  # 2. 推送镜像到 Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/linear-algebra-mastery:$COMMIT_SHA']

  # 3. 部署到 Cloud Run (服务名: linear-algebra-mastery)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'linear-algebra-mastery'
      - '--image'
      - 'gcr.io/$PROJECT_ID/linear-algebra-mastery:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/linear-algebra-mastery:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
